'use client';

import React, { useState } from 'react';
import { useSession } from '@/lib/SessionContext';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  FileText,
  User,
  Stethoscope,
  History as HistoryIcon,
  Pill,
  Users,
  Briefcase,
  Sparkles,
  Download,
  RotateCcw,
  CheckCircle2,
  Save,
  LogOut,
} from 'lucide-react';
import { generateClinicalSummary } from '@/lib/ai-actions';
import { toast } from 'sonner';
import ReactMarkdown from 'react-markdown';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

export function SummaryView() {
  const session = useSession();
  const [report, setReport] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isEndDialogOpen, setIsEndDialogOpen] = useState(false);

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    try {
      // Map session context to the format expected by AI actions
      const sessionData = {
        id: 'current-session',
        startTime: Date.now(),
        mode: session.mode,
        currentStage: session.currentStage,
        data: {
          biodata: session.biodata || {},
          presentingComplaints: session.presentingComplaints,
          hpcData: session.hpcData,
          pmh: session.pmhData,
          drugHistory: session.dhData,
          familyHistory: session.fhData,
          socialHistory: session.shData,
          ros: session.rosData,
        },
      };

      const result = await generateClinicalSummary(sessionData as any);
      setReport(result);
      toast.success('Clinical report generated!');
    } catch (error) {
      console.error(error);
      toast.error('Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleResetSession = () => {
    if (
      confirm(
        'Are you sure you want to reset this session? All data will be cleared.',
      )
    ) {
      window.localStorage.clear();
      window.location.reload();
    }
  };

  const downloadAsDoc = () => {
    if (!report) return;

    // A simple HTML structure that Word interprets well
    const content = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>Clinical Report</title></head>
      <body>
        <div style="font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6;">
          <h1 style="color: #000; text-transform: uppercase;">Clinical Clerkship Report</h1>
          <p style="color: #666; font-size: 12px;">Generated by HX Pal on ${new Date().toLocaleDateString()}</p>
          <hr />
          <div style="white-space: pre-wrap;">
            ${report.replace(/\n/g, '<br/>')}
          </div>
        </div>
      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff', content], {
      type: 'application/msword',
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Clinical_Report_${session.biodata?.name || 'Session'}_${new Date().toISOString().split('T')[0]}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success('Downloading report...');
  };

  const handleFinalizeSession = (save: boolean) => {
    if (save) {
      // Future: persists to DB
      toast.success('Session saved to database (coming soon!)');
    }

    window.localStorage.clear();
    window.location.href = '/dashboard';
  };

  // Render Helpers
  const renderFamilyHistory = () => {
    if (!session.fhData) return 'None recorded';
    try {
      const parsed = JSON.parse(session.fhData);
      const relatives = parsed.relatives || [];
      if (relatives.length === 0 && !parsed.notes) return 'None recorded';

      return (
        <div className='text-xs space-y-3'>
          {relatives.length > 0 && (
            <ul className='list-disc pl-4 space-y-1'>
              {relatives.map((r: any, i: number) => (
                <li key={i}>
                  <span className='font-bold'>{r.relation}</span> ({r.status}):{' '}
                  {r.condition}
                  {r.ageOfOnset && ` (Onset: ${r.ageOfOnset})`}
                </li>
              ))}
            </ul>
          )}
          {parsed.notes && (
            <div className='pt-1'>
              <p className='text-[10px] uppercase font-bold text-muted-foreground mb-1'>
                Additional Notes
              </p>
              <p className='italic'>{parsed.notes}</p>
            </div>
          )}
        </div>
      );
    } catch (e) {
      return session.fhData;
    }
  };

  const renderSocialHistory = () => {
    if (!session.shData) return 'None recorded';
    try {
      const parsed = JSON.parse(session.shData);
      return (
        <div className='text-xs space-y-3'>
          <div className='grid grid-cols-2 gap-2 text-[10px]'>
            {parsed.tobacco && (
              <div className='p-2 bg-muted/30 border border-border/50'>
                <p className='font-bold uppercase text-muted-foreground mb-1'>
                  Tobacco
                </p>
                <p className='text-xs font-medium'>{parsed.tobacco.status}</p>
                {parsed.tobacco.packYears > 0 && (
                  <p className='text-primary font-bold'>
                    {parsed.tobacco.packYears} Pack-years
                  </p>
                )}
              </div>
            )}
            {parsed.alcohol && (
              <div className='p-2 bg-muted/30 border border-border/50'>
                <p className='font-bold uppercase text-muted-foreground mb-1'>
                  Alcohol
                </p>
                <p className='text-xs font-medium'>{parsed.alcohol.status}</p>
                {parsed.alcohol.unitsPerWeek > 0 && (
                  <p className='text-primary font-bold'>
                    {parsed.alcohol.unitsPerWeek} Units/week
                  </p>
                )}
              </div>
            )}
          </div>

          <div className='space-y-2'>
            {parsed.livingSituation && (
              <div>
                <p className='text-[10px] uppercase font-bold text-muted-foreground'>
                  Living Situation
                </p>
                <p>{parsed.livingSituation}</p>
              </div>
            )}
            {parsed.extraNotes && (
              <div>
                <p className='text-[10px] uppercase font-bold text-primary'>
                  Obstetric / Extra Context
                </p>
                <p className='italic'>{parsed.extraNotes}</p>
              </div>
            )}
          </div>
        </div>
      );
    } catch (e) {
      return session.shData;
    }
  };

  const renderHpc = () => {
    const hpcEntries = Object.entries(session.hpcData);
    if (hpcEntries.length === 0) return 'None recorded';

    return (
      <div className='text-xs space-y-4'>
        {hpcEntries.map(([id, data]) => {
          const complaint = session.presentingComplaints.find(
            (c) => c.id === id,
          );
          return (
            <div
              key={id}
              className='border-l-2 border-primary/20 pl-3 space-y-1'
            >
              <p className='font-bold text-primary uppercase text-[10px] mb-1'>
                {complaint?.complaint || 'Unidentified Complaint'}
              </p>
              {typeof data.character === 'string' ? (
                <p>{data.character}</p>
              ) : (
                <div className='grid grid-cols-2 gap-x-4 gap-y-1 text-[10px]'>
                  <p>
                    <strong>Site:</strong> {data.character.site || 'N/A'}
                  </p>
                  <p>
                    <strong>Onset:</strong> {data.character.onset || 'N/A'}
                  </p>
                  <p>
                    <strong>Severity:</strong>{' '}
                    {data.character.severity || 'N/A'}
                  </p>
                  <p>
                    <strong>Exac/Rel:</strong>{' '}
                    {data.character.exacerbatingRelieving || 'N/A'}
                  </p>
                </div>
              )}
              <div className='pt-1 text-[10px] italic text-muted-foreground'>
                <p>Course: {data.course}</p>
                <p>Cause: {data.cause}</p>
              </div>
            </div>
          );
        })}
      </div>
    );
  };

  const renderPmh = () => {
    if (!session.pmhData) return 'None recorded';
    try {
      const parsed = JSON.parse(session.pmhData);
      const conditions = parsed.conditions || [];
      if (conditions.length === 0 && !parsed.surgicalHistory && !parsed.notes)
        return 'None recorded';

      return (
        <div className='text-xs space-y-3'>
          {conditions.length > 0 && (
            <div className='space-y-1'>
              <p className='text-[10px] uppercase font-bold text-muted-foreground'>
                Conditions
              </p>
              <ul className='list-disc pl-4'>
                {conditions.map((c: any, i: number) => (
                  <li key={i}>
                    <span className='font-bold'>{c.condition}</span>
                    {c.duration && ` (${c.duration})`}
                    {c.managedBy && ` - Managed by ${c.managedBy}`}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {parsed.surgicalHistory && (
            <div>
              <p className='text-[10px] uppercase font-bold text-muted-foreground'>
                Surgical History
              </p>
              <p>{parsed.surgicalHistory}</p>
            </div>
          )}
          {parsed.notes && (
            <div>
              <p className='text-[10px] uppercase font-bold text-muted-foreground'>
                Notes
              </p>
              <p className='italic'>{parsed.notes}</p>
            </div>
          )}
        </div>
      );
    } catch (e) {
      return session.pmhData;
    }
  };

  const renderDh = () => {
    if (!session.dhData) return 'None recorded';
    try {
      const parsed = JSON.parse(session.dhData);
      const medications = parsed.medications || [];
      const allergies = parsed.allergies || [];

      if (
        medications.length === 0 &&
        !parsed.nkda &&
        allergies.length === 0 &&
        !parsed.notes
      )
        return 'None recorded';

      return (
        <div className='text-xs space-y-4'>
          {medications.length > 0 && (
            <div className='space-y-1'>
              <p className='text-[10px] uppercase font-bold text-muted-foreground'>
                Current Medications
              </p>
              <ul className='list-disc pl-4'>
                {medications.map((m: any, i: number) => (
                  <li key={i}>
                    <span className='font-bold'>{m.name}</span>
                    {m.notes && `: ${m.notes}`}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className='space-y-1'>
            <p className='text-[10px] uppercase font-bold text-red-500'>
              Allergies
            </p>
            {parsed.nkda ? (
              <p className='text-green-600 font-medium'>
                No Known Drug Allergies (NKDA)
              </p>
            ) : allergies.length > 0 ? (
              <ul className='list-disc pl-4 text-red-600'>
                {allergies.map((a: any, i: number) => (
                  <li key={i}>
                    <span className='font-bold'>{a.agent}</span>: {a.reaction} (
                    {a.severity})
                  </li>
                ))}
              </ul>
            ) : (
              <p className='italic text-muted-foreground'>None recorded</p>
            )}
          </div>

          {parsed.notes && (
            <div>
              <p className='text-[10px] uppercase font-bold text-muted-foreground'>
                Notes
              </p>
              <p className='italic'>{parsed.notes}</p>
            </div>
          )}
        </div>
      );
    } catch (e) {
      return session.dhData;
    }
  };

  const renderRos = () => {
    if (!session.rosData) return 'None recorded';
    const entries = Object.entries(session.rosData).filter(([_, val]) => val);
    if (entries.length === 0) return 'None recorded';

    return (
      <div className='text-xs grid grid-cols-1 gap-2'>
        {entries.map(([system, notes]) => (
          <div
            key={system}
            className='border-l-2 border-primary/10 pl-2'
          >
            <p className='text-[10px] font-bold uppercase text-muted-foreground'>
              {system}
            </p>
            <p>{notes as string}</p>
          </div>
        ))}
      </div>
    );
  };

  return (
    <div className='flex flex-col h-full max-w-4xl mx-auto p-4 md:p-6 space-y-6 overflow-y-auto pb-32'>
      <div className='space-y-2'>
        <h2 className='text-2xl font-black uppercase tracking-tighter flex items-center gap-2'>
          <CheckCircle2 className='w-8 h-8 text-primary' />
          Review & Complete
        </h2>
        <p className='text-sm text-muted-foreground'>
          Review the collected history and generate a professional clinical
          report.
        </p>
      </div>

      <div className='grid gap-6'>
        {/* Main AI Action */}
        <div className='flex flex-col gap-4 p-6 border-2 border-primary/20 bg-primary/5'>
          <div className='flex items-center gap-3'>
            <div className='p-2 bg-primary/10 rounded-full'>
              <Sparkles className='w-5 h-5 text-primary' />
            </div>
            <div>
              <h3 className='font-bold uppercase tracking-tight'>
                Generate Clinical Report
              </h3>
              <p className='text-xs text-muted-foreground text-balance'>
                Let HX Pal synthesize all your findings into a standard clinical
                clerkship format.
              </p>
            </div>
          </div>
          <div className='flex flex-col sm:flex-row gap-3'>
            <Button
              className='flex-1 gap-2 font-bold uppercase tracking-wider'
              onClick={handleGenerateReport}
              disabled={isGenerating}
            >
              <Sparkles className='w-4 h-4' />
              {isGenerating ? 'Synthesizing...' : 'Synthesize Report'}
            </Button>
          </div>
        </div>

        {/* AI Report Output */}
        {report && (
          <Card className='border-2 border-primary shadow-[4px_4px_0px_0px_rgba(0,0,0,0.1)] overflow-hidden'>
            <CardHeader className='bg-primary text-primary-foreground py-3'>
              <CardTitle className='text-sm font-bold uppercase tracking-widest flex items-center gap-2'>
                <FileText className='w-4 h-4' />
                Formal Clinical Clerkship
              </CardTitle>
            </CardHeader>
            <CardContent className='p-6 prose prose-sm max-w-none dark:prose-invert bg-white dark:bg-zinc-950'>
              <ReactMarkdown>{report}</ReactMarkdown>
            </CardContent>
          </Card>
        )}

        {/* Data Review Grid */}
        <div className='grid gap-4 md:grid-cols-2'>
          <SummaryCard
            title='Biodata'
            icon={<User className='w-4 h-4' />}
            content={
              session.biodata ? (
                <div className='text-xs space-y-1'>
                  <p>
                    <strong>Name:</strong> {session.biodata.name || '---'}
                  </p>
                  <p>
                    <strong>Age:</strong> {session.biodata.age || '---'}
                  </p>
                  <p>
                    <strong>Sex:</strong> {session.biodata.gender || '---'}
                  </p>
                  <p>
                    <strong>Occupation:</strong>{' '}
                    {session.biodata.occupation || '---'}
                  </p>
                </div>
              ) : (
                'No biodata recorded'
              )
            }
          />

          <SummaryCard
            title='HPI (History of Presenting Complaint)'
            icon={<Stethoscope className='w-4 h-4' />}
            content={renderHpc()}
          />

          <SummaryCard
            title='Past Medical History'
            icon={<HistoryIcon className='w-4 h-4' />}
            content={renderPmh()}
          />

          <SummaryCard
            title='Drug History & Allergies'
            icon={<Pill className='w-4 h-4' />}
            content={renderDh()}
          />

          <SummaryCard
            title='Family History'
            icon={<Users className='w-4 h-4' />}
            content={renderFamilyHistory()}
          />

          <SummaryCard
            title='Social History'
            icon={<Briefcase className='w-4 h-4' />}
            content={renderSocialHistory()}
          />

          <SummaryCard
            title='Review of Systems'
            icon={<Sparkles className='w-4 h-4' />}
            content={renderRos()}
          />
        </div>

        <div className='pt-12 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4'>
          <Button
            variant='ghost'
            size='sm'
            className='text-destructive hover:bg-destructive/10 gap-2 justify-center sm:justify-start'
            onClick={handleResetSession}
          >
            <RotateCcw className='w-4 h-4' />
            Reset Session Data
          </Button>

          <div className='flex flex-col sm:flex-row gap-3 w-full sm:w-auto'>
            <Button
              variant='outline'
              className='gap-2 justify-center'
              disabled={!report}
              onClick={downloadAsDoc}
            >
              <Download className='w-4 h-4' />
              Download Report (.doc)
            </Button>
            <Button
              className='gap-2 justify-center'
              onClick={() => setIsEndDialogOpen(true)}
            >
              <LogOut className='w-4 h-4' />
              End Session
            </Button>
          </div>
        </div>
      </div>

      {/* End Session Dialog */}
      <Dialog
        open={isEndDialogOpen}
        onOpenChange={setIsEndDialogOpen}
      >
        <DialogContent className='sm:max-w-md bg-white dark:bg-zinc-950 border-2 border-primary/20 rounded-none shadow-xl'>
          <DialogHeader>
            <DialogTitle className='uppercase tracking-tighter font-black text-2xl flex items-center gap-2'>
              <CheckCircle2 className='w-6 h-6 text-primary' />
              Complete Session?
            </DialogTitle>
            <DialogDescription className='text-sm text-muted-foreground'>
              You are about to close this clinical session. Would you like to
              save the data for future reference?
            </DialogDescription>
          </DialogHeader>
          <div className='bg-primary/5 p-4 border border-primary/10 text-xs italic text-muted-foreground mb-4'>
            Note: "Saving session" will persist this clerkship to your dashboard
            database once the feature is fully rolled out.
          </div>
          <DialogFooter className='flex flex-row! gap-3 sm:justify-between sm:space-x-0'>
            <Button
              variant='outline'
              className='flex-1 gap-2 border-2 rounded-none'
              onClick={() => handleFinalizeSession(false)}
            >
              Discard & End
            </Button>
            <Button
              className='flex-1 gap-2 rounded-none font-bold uppercase'
              onClick={() => handleFinalizeSession(true)}
            >
              <Save className='w-4 h-4' />
              Save & End
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

function SummaryCard({
  title,
  icon,
  content,
}: {
  title: string;
  icon: React.ReactNode;
  content: React.ReactNode;
}) {
  return (
    <Card className='h-full border-2 border-border/50 rounded-none shadow-none hover:border-primary/50 transition-colors'>
      <CardHeader className='py-3 px-4 flex flex-row items-center justify-between space-y-0 pb-2 border-b border-border/10'>
        <CardTitle className='text-[10px] font-bold uppercase tracking-widest'>
          {title}
        </CardTitle>
        <div className='text-muted-foreground/50'>{icon}</div>
      </CardHeader>
      <CardContent className='px-4 py-4'>
        <div className='text-sm'>{content}</div>
      </CardContent>
    </Card>
  );
}
